### PR TITLE
Net4j: support secure websocket connections #25

### PR DESCRIPTION
**Pull request by mPorhel**
Report of our WSS implementation based on CDO 4.7 to CDO master (commits for 4.22, to adapt for 4.25)

### CODE REVIEW

**Comment by claesrosell** [comment]
For testing, I tried to build this now and it looks like there is a missing, new, dependency from the org.eclipse.net4j.ws bundle to org.eclipse.core.net .
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.5:validate-classpath (default-validate-classpath) on project org.eclipse.net4j.ws: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.5:validate-classpath failed: org.osgi.framework.BundleException: Bundle org.eclipse.net4j.ws cannot be resolved:org.eclipse.net4j.ws [40]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.core.net; bundle-version="[1.4.0,1.5.0)"
```

**Comment by mPorhel** [comment]
Hi Claes, 

I will check the tp and pom in the end of the afternoon, I might have missed something during rebase on master.

Regards

**Comment by merks** [comment]
FYI, keep in mind that the *.target is generated when the targlets task resolves the target platform...

**Comment by mPorhel** [comment]
Hi Ed, 

This was my current point of investigation, in my commits and in my local build I have modified the .target. 
It seems I have to check the .targlets.

Regards

**Comment by merks** [comment]
I expect Eike to help at some point...  

I think you just need to do Help -> Perform Setup Tasks and when the Targlets task is performed, it will update the target as a side effect (or it will fail).   I'll try it myself, see how that works, and get back to you in a few minutes.

**Comment by merks** [comment]
Please edit the setup to remove that requirement. You can use Ctrl-F to find it.   It's not needed anymore and not available anymore.

**Comment by merks** [comment]
Creating a fresh development environment and pulling your PR into it should help.   Dragging this link and dropping it onto the installer gave me a clean environment:

https://raw.githubusercontent.com/eclipse-cdo/cdo/master/releng/org.eclipse.emf.cdo.releng/CDOConfiguration.setup

When I try that though, I see what you see:

>   ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1698068395707
>   ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Net4j Signalling Platform Websocket Transport 1.2.2.v20231023-153953 (org.eclipse.net4j.ws 1.2.2.v20231023-153953) requires 'osgi.bundle; org.eclipse.core.net [1.4.0,1.5.0)' but it could not be found
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1698068395707
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.emf.cdo.all.feature.group 0.0.0
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: CDO Model Repository All 4.24.0.v20231023-153953 (org.eclipse.emf.cdo.all.feature.group 4.24.0.v20231023-153953)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.net4j.tests.feature.group 0.0.0
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Net4j Signalling Platform Tests 4.2.11.v20231023-153953 (org.eclipse.net4j.tests 4.2.11.v20231023-153953)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.net4j.ws [1.0.0,2.0.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Net4j Signalling Platform Tests 4.3.11.v20231023-153953 (org.eclipse.net4j.tests.feature.group 4.3.11.v20231023-153953)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.net4j.tests 0.0.0

There are a bunch of very narrow range restrictions.  When I expand that range, the next failure is this:

> org.apache.aries.spifly.dynamic.bundle [1.3.3,1.3.4)' but it could not be found

I think this really needs @estepper's attention.

**Comment by mPorhel** [comment]
In the provided commits, I add

*  the following plugins as "requires/import" on net4j-ws.feature:
** "org.apache.aries.spifly.dynamic.bundle" version="1.3.3"
** "org.objectweb.asm" version="9.1.0"
** "org.objectweb.asm.commons" version="9.1.0"
** "org.objectweb.asm.tree" version="9.1.0" 
** "org.objectweb.asm.tree.analysis" version="9.1.0" 
** "org.objectweb.asm.util" version="9.1.0" match="perfect"/>
* plugin  org.eclipse.core.net;bundle-version="[1.4.0,1.5.0)" as required bundle in net4j.ws plugin

In our local fork, built internally, I have modified the .target to add 
 ```
<location includeDependencyScope="compile" includeSource="true" missingManifest="generate" type="Maven">
      <dependencies>
        <dependency>
          <groupId>org.apache.aries.spifly</groupId>
          <artifactId>org.apache.aries.spifly.dynamic.bundle</artifactId>
          <version>1.3.3</version>
          <type>jar</type>
        </dependency>
      </dependencies>
    </location>
```

I will check how to add this into the targlets

**Comment by merks** [comment]
Note that aries is available in the platform repo and was already available in 4.29 too:

image

**Comment by mPorhel** [comment]
Hi @merks 

After updating the Aries, objectweb and core.net dependencies to the versions available in the new tp (was indirectly blocked on CDO 4.22 on my broken env), I was able to perform the update tasks by Oomph and I now have an updated .target.

There is now the new Big Thing: Net4J.WS is tailord for Jetty 10.0.x but Eclipse 2023-12 has moved to Jetty 12.


@claesrosell which version of CDO do you use ? or target ? In which version of Eclipse do you expect to run the websockets?

**Comment by merks** [comment]
Yes, the whole Jetty 12 thing is a bit of a nightmare for those downstream, especially given that some of the Jetty ee8 stuff was missing too.  Fortunately the help jetty folks are working on:

**Comment by mPorhel** [comment]
@claesrosell having the two Jetty 12 and 10 as resolved dependencies in my CDO env, I got a compilation error in WSSClientConnector, line 96 
I have added a new commit to the PR to avoid this compilation error 
Possible workarounds to use self-signed certificates:  install the certificate in your current JDK cacert or use -Dorg.eclipse.net4j.internal.wss.ssl.trustall=true

I have not tested Net4J.WS nor Net4J.WSS on CDO master / 4.25 i-build for now. 
Jetty 12 might not be able to ini Jetty 10.0.6 websockets.

org.eclipse.net4j.tests.config.TestConfig.WS and org.eclipse.net4j.tests.config.TestConfig.WSS will allow you to try them :  they are referenced in org.eclipse.net4j.tests.AllTests.suite()

**Comment by openMonArch** [comment]
We are using wss with jetty 11 and it works fine. So using Jetty 12 is my option, with the choice to move on in the future.
We are also using "io.github.hakky54" to make handling certificates much easier because self-signed certificates are a mess in production environments.
 `
 <dependency>
  <groupId>io.github.hakky54</groupId>
  <artifactId>sslcontext-kickstart-for-pem</artifactId>
</dependency>
`
`
<dependency>
 <groupId>io.github.hakky54</groupId>
 <artifactId>sslcontext-kickstart-for-jetty</artifactId>
</dependency>
`

**Comment by claesrosell** [comment]
We are currently using CDO 4.17 and Jetty-10 and are using Websockets in that environment. But if everything goes well, we will be targeting Eclipse 2023-12 with Jetty-12 and CDO 4.25.

**Comment by claesrosell** [comment]
With these latest commits, I get CDO to build on my setup. I will try to find time to test soon.

**Comment by mPorhel** [comment]
With the latest commit, I have been able to locally run the unit tests with WS/WSS and the current TP: 
* org.eclipse.emf.cdo.tests.AllTestsWS: 1 error, 1 failure on 11816 tests
  * Scenario[MEM, WSS, Native]
    * _Error_ org.eclipse.emf.cdo.tests.LockingNotificationsTest.testSameBranchDifferentSession_WithAutoRelease()
  * Scenario [MEM-auditing-Legacy]
    * _Failure_ org.eclipse.emf.cdo.tests.bugzilla.Bugzilla_387564_Test.testLockEventAfterInvalidationEventDifferentSession()
* org.eclipse.emf.cdo.tests.AllTestsWSS: 1 error, 1 failure on 11816 tests
  * see AllTestsWS details
* org.eclipse.net4j.tests.AllTests: 2 failures, 0 error on 265 tests
  * 2 failures in org.eclipse.net4j.util.tests.RollingLogTest: not related to current PR
  * before the PR, I get the same 2 failures on 219 tests

The APIs to launch the server in the test config launches a Jetty 10.x server.

**Comment by merks** [comment]
@merks @claesrosell @estepper 

This is has gone stale.  Is there still needed/wanted?

**Comment by mPorhel** [comment]
This is used on production on forked versions of CDO 4.7 and CDO 4.22 on my side, and @claesrosell  might also use it.
I should be able to take some time in the upcoming weeks to realign it with CDO master and update the PR.

**Comment by claesrosell** [comment]
We are using this, but we are building CDO from is PR "on our own" since this PR is not accepted yet. 

@mPorhel, what do you think about the Jetty-10/Jetty-12 situation? Since Equinox has moved to Jetty 12 I would personally like to see this PR moved to that as well. However it looks like CDO master is still on Jetty-10. With that said, I think that the only parts using Jetty in CDO are the web-socket stuff. I might be wrong though.

**Comment by merks** [comment]
Help getting cdo working with jetty 12 would be great. I think @estepper tried but got stuck.

**Comment by mPorhel** [comment]
@claesrosell @merks  I agree for the move of Jetty version: it should be aligned with the targeted version of the platform.
I am not sur that the move to Jetty 12 is only linked to this PR : the standard WebSocket transport is already in CDO/Net4J.

On our side we are still on Eclipse 2023-03 with Jetty moved to 10.0.20 so for the moment I have for the moment no clue for this part of the adaptation to CDO master.

**Comment by claesrosell** [comment]
I can make an attempt to get CDO master to work with Jetty-12 in a couple of weeks.

**Comment by openMonArch** [comment]
We were using Eclipse 2021-03 with CDO R20220116-1034 in production with our own secure websocket implementation on Jetty 11.
We have now moved to Eclipse 2024-03 with CDO R20220116-1034 and 4.26.0 and Jetty 11. 
Both versions work fine. We use sslcontest-kickstart-for-jetty in our secure implementation to use letsencrypt cert directly. So if this part is interesting, I would be happy to contribute.

**Comment by estepper** [comment]
Hey Guys, I apologize for the long delay here. Now I wanted to rebase this PR and review/merge it, but I'm still not familiar with the needed steps. Is it perhaps easier that the last committer here does the rebase? I promise to start the review immediately then ;-)

**Comment by claesrosell** [comment]
@mPorhel, would it be possible for you to rebase this PR to master?

**Comment by mPorhel** [comment]
Hi Claes, 

I have juste re-installed the CDO dev environment using Eclipse installer with Eclipse 2024 and CDO master.
Tp is ok, standard tests seems to run fine.

WS tests are KO: 
```
[ERROR] org.eclipse.jetty.websocket.core.exception.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 500 Server Error
org.eclipse.jetty.websocket.api.exceptions.UpgradeException: org.eclipse.jetty.websocket.core.exception.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 500 Server Error
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandler.convertCause(JettyWebSocketFrameHandler.java:532)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandler.onError(JettyWebSocketFrameHandler.java:258)
	at org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest.handleException(CoreClientUpgradeRequest.java:247)
	at org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest.onComplete(CoreClientUpgradeRequest.java:235)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:213)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:205)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:477)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:457)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:420)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:386)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:587)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1727)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1556)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:221)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:160)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:91)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.jetty.websocket.core.exception.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 500 Server Error
	... 22 more
```

So there is a first step of "fixing WS connector/acceptor" before rebasing the PR.

**Comment by mPorhel** [comment]
CDO.setup still reference Jetty 10.0.15 repository (https://download.eclipse.org/oomph/jetty/release/10.0.15) in which is takes the org.eclipse.jetty.websocket.* features/plugins.

CDO/Net4J other dependencies to Jetty has moved from [10.0.0, 11.0.0) to [12.0.0, 13.0.0). 
Eclipse 2024-09 uses Eclipse Jetty 12.0.11.
We might need to move to the Jetty websocket 12.0.11 plugins too.
There is no more need to use Oomph repo: https://download.eclipse.org/tools/orbit/simrel/maven-jetty/release/12.0.11/

There are core/ee8/ee9/ee10 plugins. Eclipse platform uses ee8 server plugins for the help system.
I am currently trying to fix the tp and adapt the code.

**Comment by mPorhel** [comment]
I currenly have a working environment with ws://  with CDO master / Eclipse 2024-09 / Jetty 12.

To sum-up the situation with shortcuts:  during recent tp updates  the net4j.ws client code has moved from Jetty 10 behavior to Jetty 12 specific  implementation and not the test server which is also not able to deploy the current servlet.
I have a pretty simples set of changes (mainly addition of .ee8. in qualified names and dependencies + releng/tp + one fix) and org.eclipse.emf.cdo.tests.AllTestsWS having no error nor failure for its 11823 tests 


> Jetty provides different implementations of the WebSocket protocol:
>   * A Jakarta EE 8 (javax.websocket) implementation, based on the [Jakarta WebSocket 1.1 Specification](https://jakarta.ee/specifications/websocket/1.1/).
>  * A Jakarta EE 9 (jakarta.websocket) implementation, based on the [Jakarta WebSocket 2.0 Specification](https://jakarta.ee/specifications/websocket/2.0/).
> * A Jakarta EE 10 (jakarta.websocket) implementation, based on the [Jakarta WebSocket 2.1 Specification](https://jakarta.ee/specifications/websocket/2.1/).
>  * A Jetty specific implementation, based on the Jetty WebSocket APIs, that does not depend on any Jakarta EE APIs.
https://jetty.org/docs/jetty/12/programming-guide/server/websocket.html

I will try to cleanup my environment and provide a PR this afternoon for this first step and then rebase this PR on it.

I have one change in the tp which is automatically done without any change on my side reverting [this commit](https://github.com/eclipse-cdo/cdo/commit/65a3b0f656cc58bc22feb88ab5f0faf38af9c63f) from  @estepper

**Comment by merks** [comment]
FYI, I frequently find generated *.target files oscillating between slf4j.nop and slf4j.simple, e.g., with BIRT's target.  Probably because either one is a reasonable solution for p2, but it's still annoying.

**Comment by mPorhel** [comment]
@estepper @claesrosell  please see #64 a PR to fix WS support and ticket #63 

This is  mandatory and preparative step before rebasing the current PR #30.
I will look at the rebase next week.

**Comment by mPorhel** [comment]
PR #30 rebased on top of PR #64 

org.eclipse.emf.cdo.tests.AllTestsWSS and org.eclipse.emf.cdo.tests.AllTestsWS are green on my side.

I have not tested the Cookies/proxy/trustore/keystore capabilities after the move to Jetty12 and CDO master.

**Comment by mPorhel** [comment]
@claesrosell @estepper do not hesitate to provide feedback on the two PRs #30  and #64

**Comment by claesrosell** [comment]
I will test these later this week. Maybe tomorrow but probably the day after that.

**Comment by claesrosell** [comment]
I just wanted to say that I am working on testing this in our product.  Since we currently are using embedded Jetty 10 there is some work to migrate to Jetty 12. Hopefully, I will be done with that on Monday.

**Comment by claesrosell** [comment]
I can confirm that these PRs are working in our environment. Thank you  @mPorhel . Hopefully @estepper can review this PR soon.

**Comment by estepper** [comment]
Thank you a lot guys!!! Starting to squash, rebase, test, push... ;-)

**Comment by estepper** [comment]
I've squashed those many commits in the PR, reviewed, tested and pushed everything. A nightly build was successful, the I-build I20241120-0740 is running and will be available soon.

Thank you all again ;-)

**Comment by mPorhel** [comment]
Thanks @estepper !

**Pull request closed without merging**
