### PR TITLE
[GMF Notation] Use the getXXXGen() getters in eIsSet() method

### PR DESCRIPTION
**Pull request by vsennedot**
#53

### CODE REVIEW

**Comment by merks** [comment]
FYI, there is currently an infrastructure problem causing the build failure:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4884

**Comment by estepper** [comment]
I've just updated the master branch so that it can build 4.29...

**Comment by merks** [comment]
@estepper 

Is there anything holding this up?  Are there tests that these these changes?

Note that the PR contains a merge commit where probably a rebase would be better to keep a linear commit history...

**Comment by estepper** [comment]
Hi Vincent, thank you very much! I've cherry-picked your commit locally to avoid pushing your merge commit. I've also bumbep the plugin version and pushed everthing with your author ID. Thank you again ;-)

**Pull request closed without merging**
